name: jonerik
favicon: null
layout_spectrum: 0.24875
typography_spectrum: 1
title: jonerik
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191919'
    - '#aa513d'
    - '#cd8778'
    - '#662720'
    - '#2f535d'
  brandStrength: 0.1875
  lightness: 0.4375
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
