name: jonerik
favicon: null
layout_spectrum: 0.24875
typography_spectrum: 1
title: jonerik
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#131313'
    - '#141414'
    - '#101010'
    - '#111111'
    - '#141414'
  brandStrength: 0.1875
  lightness: 0.4375
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
