name: jonerik
favicon: null
layout_spectrum: 0.03884313860908151
typography_spectrum: 0.29764099488966167
title: jonerik
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#131313'
    - '#141414'
    - '#101010'
    - '#111111'
    - '#141414'
  brandStrength: 0.1875
  lightness: 0.24181823711842299
  saturation: 0.08361825300380588
  rhythmicContrast: 0.8130462230183184
purpose: []
